version: '2.3'
services:
  websocket-app:
    image: app
    environment:
      - APPLICATION_RABBITMQ_HOST=rabbitmq
      - APPLICATION_RABBITMQ_PORT=61613
      - APPLICATION_RABBITMQ_LOGIN=test
      - APPLICATION_RABBITMQ_PASSCODE=test
      - SERVER_PORT=8090
      - JAVA_OPTS=-Xmx512m -Xms256m
    build:
      context: ./
      dockerfile: Dockerfile
    scale: 2

  rabbitmq:
    extends:
      service: rabbitmq
      file: rabbitmq/rabbitmq.yml
  nginx:
    extends:
      service: nginx
      file: nginx/nginx.yml
