version: '2'

services:
  rabbitmq:
    build: .
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
      - '61613:61613'
      - '15674:15674'
#    environment:
#      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
#      RABBIT_DEFAULT_USER: 'guest'
#      RABBIT_DEFAULT_PASSWORD: 'guest'
    volumes:
      - 'rabbitmq_data:/bitnami'

volumes:
  rabbitmq_data:
    driver: local
